name: Qt CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5widgets5

    # Build ZMQpush
    - name: Configure ZMQpush with qmake
      working-directory: Benthernet/ZMQpush
      run: qmake -o Makefile ZMQpush.pro

    - name: Build ZMQpush
      working-directory: Benthernet/ZMQpush
      run: make

    # Build ZMQsub
    - name: Configure ZMQsub with qmake
      working-directory: Benthernet/ZMQsub
      run: qmake -o Makefile ZMQsub.pro

    - name: Build ZMQsub
      working-directory: Benthernet/ZMQsub
      run: make

    # Run tests for ZMQpush
    - name: Run tests for ZMQpush
      working-directory: Benthernet/ZMQpush
      run: |
        if [ -f ./tests/testsuite_push ]; then
          ./tests/testsuite_push
        else
          echo "No testsuite for ZMQpush found."
        fi

    # Run tests for ZMQsub
    - name: Run tests for ZMQsub
      working-directory: Benthernet/ZMQsub
      run: |
        if [ -f ./tests/testsuite_sub ]; then
          ./tests/testsuite_sub
        else
          echo "No testsuite for ZMQsub found."
        fi
