name: Qt CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev libzmq3-dev

    - name: Build ZMQpush
      run: |
        cd Benthernet/ZMQpush
        qmake ZMQpush.pro
        make

    - name: Build ZMQsub
      run: |
        cd Benthernet/ZMQsub
        qmake ZMQsub.pro
        make
