name: Qt Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.3
        host: windows
        target: desktop
        arch: win64_msvc2019_64

    - name: Install dependencies
      run: |
        choco install -y cmake
      shell: powershell

    - name: Build ZMQsub project
      run: |
        mkdir build\ZMQsub
        cd build\ZMQsub
        qmake ../../../Benthernet/ZMQsub/ZMQsub.pro
        nmake
      shell: cmd

    - name: Build ZMQClientGUI project
      run: |
        mkdir build\ZMQClientGUI
        cd build\ZMQClientGUI
        qmake ../../../Benthernet/ZMQClientGUI/ZMQClientGUI.pro
        nmake
      shell: cmd

    - name: Run ZMQsub executable
      run: |
        cd build\ZMQsub
        ZMQsub.exe
      shell: cmd

    - name: Run ZMQClientGUI executable
      run: |
        cd build\ZMQClientGUI
        ZMQClientGUI.exe
      shell: cmd
